[package]
name = "xtask"
description = "Tasks for building, testing, maintaining, and publishing Maelsrom."
publish = false
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
cargo_metadata.workspace = true
chrono.workspace = true
clap.workspace = true
csv.workspace = true
elf.workspace = true
jsonwebtoken.workspace = true
maelstrom-linux.workspace = true
maelstrom-util.workspace = true
regex.workspace = true
reqwest = { workspace = true, features = ["form"] }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tempfile.workspace = true
url.workspace = true
versions.workspace = true
zerocopy.workspace = true

[dev-dependencies]
colored-diff.workspace = true
indoc.workspace = true
maelstrom-simex.workspace = true
maelstrom-util.workspace = true
